#! /bin/sh
restart() {
  pkill -x "$1"
  while pgrep -x "$1" >/dev/null; do sleep 0.1; done
  "$@" &
}

start_if_not_running() {
    pgrep -x "$1" >/dev/null || "$@" &
}

{
  restart nm-applet
  restart blueman-applet
  restart fusuma
  restart picom --backend glx
  restart sxhkd >~/sxhkd_output.log 2>~/sxhkd_error.log 
  start_if_not_running syncthing
  start_if_not_running alacritty
  start_if_not_running nitrogen --set-scaled ~/Downloads/Nordic-mountain-wallpaper.jpeg

  if xrandr | grep -q "^HDMI-1 connected"; then
    bspc wm --reorder-monitors HDMI-1 eDP-1
    dunstify -a "BSPWM" "INFO" "External monitor detected!" -r 5551
    bspc monitor HDMI-1 -d 1 2 3 4
    bspc monitor eDP-1 -d 5 6 7 8
    xrandr --output HDMI-1 --auto --primary --mode 1920x1080 --rotate normal --left-of eDP-1
    xrandr --output eDP-1 --mode 1920x1080 --rotate normal
  else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
    xrandr --output eDP-1 --mode 1920x1080 --rotate normal
  fi

  bspc config border_width 2
  bspc config window_gap 8
  bspc config bottom_padding 35
  bspc config top_padding 0

  bspc config split_ratio 0.5
  bspc config borderless_monocle true
  bspc config gapless_monocle false
  bspc config focus_follows_pointer false
  bspc config pointer_follows_monitor false

  bspc rule -r "*"
  bspc config external_rules_command "$(which bspwm-external-rules)"
  ~/bin/polybar.launch.sh &
  
  dunstify -a "BSPWM" "INFO" "BSPWM loaded @ \n$(date)" -r 5552
  # sleep 8 ; ~/bin/bg.sh ~/Downloads/mylivewallpapers-com-Chill-Beach.mp4 && echo "1" > ~/bspwm.log && bspc rule -a '*' -o state=fullscreen layer=below
} >~/.bspwm_output.log 2>~/.bspwm_error.log &
